plugins {
	id 'java'
	id 'org.springframework.boot' version '3.4.1'
	id 'io.spring.dependency-management' version '1.1.7'

	id 'org.asciidoctor.jvm.convert' version '3.3.2'
}

group = 'com.mercury'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}

	asciidoctorExt
}

repositories {
	mavenCentral()
}
dependencyManagement {
	imports {
		mavenBom "com.google.cloud:spring-cloud-gcp-dependencies:4.8.0" // 최신 버전
	}
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-websocket'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	//rabbitmq
	implementation 'org.springframework.boot:spring-boot-starter-amqp'
	//spring messaging(stomp지원)
	implementation 'org.springframework:spring-messaging'
	//RabbitMQ에서 브로커 연결 및 통신 설정을 위해 기본으로 사용됨
	implementation 'io.projectreactor.netty:reactor-netty:1.1.13'
	testImplementation 'org.springframework.amqp:spring-rabbit-test'
	testImplementation 'org.testcontainers:rabbitmq'
	compileOnly 'org.projectlombok:lombok'
	developmentOnly 'org.springframework.boot:spring-boot-devtools'
	runtimeOnly 'com.mysql:mysql-connector-j'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.springframework.security:spring-security-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

	// build.gradle
	testImplementation 'com.h2database:h2'

	//gcp
	implementation 'com.google.cloud:spring-cloud-gcp-starter'
	implementation 'com.google.cloud:spring-cloud-gcp-starter-storage'
	//gcp error로 추가
	implementation 'com.google.code.gson:gson:2.11.0'

	// Rest Docs
	asciidoctorExt 'org.springframework.restdocs:spring-restdocs-asciidoctor'
	testImplementation 'org.springframework.restdocs:spring-restdocs-mockmvc'

	//QueryDSL
	implementation 'com.querydsl:querydsl-jpa:5.0.0:jakarta'
	annotationProcessor "com.querydsl:querydsl-apt:${dependencyManagement.importedProperties['querydsl.version']}:jakarta"
	annotationProcessor "jakarta.annotation:jakarta.annotation-api"
	annotationProcessor "jakarta.persistence:jakarta.persistence-api"

	// Redis
	implementation 'org.springframework.boot:spring-boot-starter-data-redis'


	// JWT
	implementation "io.jsonwebtoken:jjwt:0.12.3"

	// oauth
	implementation "org.springframework.boot:spring-boot-starter-oauth2-client"

	/* Apache commons-io */
	implementation 'commons-io:commons-io:2.11.0'
	/* Apache Commons Fil */
	implementation group: 'commons-fileupload', name: 'commons-fileupload', version: '1.4'

}

ext {
snippetsDir = file('build/generated-snippets')
}

test {
outputs.dir snippetsDir
}

asciidoctor {
inputs.dir snippetsDir
configurations 'asciidoctorExt'
dependsOn test
}

bootJar {
dependsOn asciidoctor
copy {
    from asciidoctor.outputDir
    into 'src/main/resources/static/docs'
}

}
clean {
delete file('src/main/generated')
}

tasks.named('test') {
useJUnitPlatform()
}
